#!/bin/bash
#/etc/init.d/gpio-btnReboot
### BEGIN INIT INFO
# Provides:           python /opt/gpio/btnReboot.py
# Required-Start:     $local_fs $syslog
# Required-Stop:      $local_fs $syslog
# Default-Start:      2 3 4 5
# Default-Stop:       0 1 6
# Short-Description:  Start gpio-btnReboot
### END INIT INFO

case "$1" in
  start)
  echo "Starting gpio-btnReboot"
  python /opt/gpio/btnReboot.py &
  ;;
  stop)
  echo "Stopping gpio-btnReboot"
  killall python
  ;;
  *)
  echo "Useage: /etc/init.d/gpio-btnReboot{start|stop}"
  exit 1
  ;;
esac

exit 0
